### ISSUE TITLE
Login information

### ISSUE THREAD

**Issue by crepppy** [DerTetrisTypAusDerSchule/Yeet#1]
Hey dude, your login information is on your github and your password is the same for all your accounts. I'd change this ;)

**Comment by crepppy** [comment]
@DerTetrisTypAusDerSchule

**Comment by DerTetrisTypAusDerSchule** [comment]
Thanks dude. Valuable life lesson learned: Don't be fucking stupid with passwords. My reddit acc even got deleted by someone logging in xD
